bot:
  prefix: "!"
  status: "for '!help' to show you all commands"

cogs:
  admin: true
  advent_of_code: true
  beginner_cog:
    enabled: true
    from: beginner.beginner
  bump: true
  candidates: true
  challenges: true
  code_runner: true
  fun: true
  google: true
  help: true
  help_rotator: true
  kudos: true
  moderation: true
  onboarding: true
  python: true
  repeater: true
  resources: true
  role_assignment: true
  rules: true
  settings: true
  spam: true
  statistics: true
  tips: true
  user_roles: true

logging:
  format: "%(asctime)s: %(levelname)-9s %(name)-16s :: %(message)s"
  date_format: "%m/%d/%Y %I:%M:%S %p"
  level: DEBUG

resources:
  py:
    name: Python
    YouTube:
      Corey Schafer: https://www.youtube.com/c/Coreyms/playlists
      Mosh: https://www.youtube.com/playlist?list=PLTjRvDozrdlxj5wgH4qkvwSOdHLOCx10f
      FreeCodeCamp: https://www.youtube.com/playlist?list=PLWKjhJtqVAbnqBxcdjVGgT3uVR10bzTEB
    Books:
      Automate the Boring Stuff with Python: https://automatetheboringstuff.com/2e/chapter0/

  ds:
    name: Data Science & Machine Learning
    YouTube:
      Mazen Ahmed: https://www.youtube.com/channel/UCiFF3AvbzLWdRyRnQMEttqw/videos?view=0&sort=da&flow=grid
      Python Programmer: https://www.youtube.com/c/FlickThrough/featured
      Codebasics: https://www.youtube.com/playlist?list=PLeo1K3hjS3us_ELKYSj_Fth2tIEkdKXvV
      Ken Jee: https://www.youtube.com/playlist?list=PL2zq7klxX5ATPC8RuqCuTDdki3b4NqKQv
    Courses:
      Kaggle Learn: https://www.kaggle.com/learn/overview
      Google ML Course (Prior knowledge of Python, Pandas, Numpy highly recommended): https://developers.google.com/machine-learning/crash-course

  pentesting:
    name: Pentesting & Ethical Hacking
    YouTube:
      HackerSploit: https://www.youtube.com/watch?v=tHd8k54kVs8&list=PLBf0hzazHTGOEuhPQSnq-Ej8jRyXxfYvl
      Joseph Delgadillo: https://www.youtube.com/watch?v=ElWo5fd4rIU&list=PLYmlEoSHldN7HJapyiQ8kFLUsk_a7EjCw&index=1
    Courses:
      Alison.com (login required): https://alison.com/topic/learn/100096/synopsis
      Offensive Security (Metasploit course): https://www.offensive-security.com/metasploit-unleashed/

lang_aliases:
  python: py
  python3: py
  python2: py
  datascience: ds
  data science: ds
  data: ds
  hacking: pentesting
