bot:
  prefix: "!"
  status: "for '!help' to show you all commands"
  guild_id: 644299523686006834

cogs:
  admin: true
  advent_of_code: true
  beginner_cog:
    enabled: true
    from: beginner.beginner
  buddy: true
  bump: true
  candidates: true
  challenges: true
  code_runner: true
  fun: true
  google: true
  help: true
  help_rotator: false
  kudos: true
  moderation: true
  monthly_showing_off: true
  onboarding: true
  python: true
  pip: true
  repeater: true
  resources: true
  role_assignment: true
  rules: true
  settings: true
  spam: true
  statistics: true
  tips: true
  user_roles: true

  prompt_weather: true
  prompt_luck: true

logging:
  format: "%(asctime)s: %(levelname)-9s %(name)-16s :: %(message)s"
  date_format: "%m/%d/%Y %I:%M:%S %p"
  level: DEBUG

resources:
  py:
    name: Python
    YouTube:
      Corey Schafer: https://www.youtube.com/c/Coreyms/playlists
      Mosh: https://www.youtube.com/playlist?list=PLTjRvDozrdlxj5wgH4qkvwSOdHLOCx10f
      FreeCodeCamp: https://www.youtube.com/playlist?list=PLWKjhJtqVAbnqBxcdjVGgT3uVR10bzTEB
    Books:
      Automate the Boring Stuff with Python: https://automatetheboringstuff.com/2e/chapter0/
    Websites:
      Real Python (Basics Tutorials): https://realpython.com/tutorials/basics/

  ds:
    name: Data Science & Machine Learning
    YouTube:
      Statquest DS Roadmap (Important to understand the maths behind ML models): https://app.learney.me/maps/StatQuest
      Math For ML (Important to understand the maths behind ML models): https://www.youtube.com/playlist?list=PLD80i8An1OEGZ2tYimemzwC3xqkU0jKUg
      Mazen Ahmed: https://www.youtube.com/channel/UCiFF3AvbzLWdRyRnQMEttqw/videos?view=0&sort=da&flow=grid
      Python Programmer: https://www.youtube.com/c/FlickThrough/featured
      Codebasics: https://www.youtube.com/playlist?list=PLeo1K3hjS3us_ELKYSj_Fth2tIEkdKXvV
      Ken Jee: https://www.youtube.com/playlist?list=PL2zq7klxX5ATPC8RuqCuTDdki3b4NqKQv
    Courses:
      Kaggle Learn: https://www.kaggle.com/learn/overview
      Google ML Course (Check prerequisites before starting): https://developers.google.com/machine-learning/crash-course
    Data Visualisation:
      Data Visualisation Catalogue: https://datavizcatalogue.com/index.html
      Which graph to use: https://www.data-to-viz.com/
      Resource for creating graphs (Python): https://www.python-graph-gallery.com/
      Resource for creating graphs (R): https://www.r-graph-gallery.com/index.html

  pentesting:
    name: Pentesting & Ethical Hacking
    YouTube:
      HackerSploit: https://www.youtube.com/watch?v=tHd8k54kVs8&list=PLBf0hzazHTGOEuhPQSnq-Ej8jRyXxfYvl
      Joseph Delgadillo: https://www.youtube.com/watch?v=ElWo5fd4rIU&list=PLYmlEoSHldN7HJapyiQ8kFLUsk_a7EjCw&index=1
    Courses:
      Alison.com (login required): https://alison.com/topic/learn/100096/synopsis
      Offensive Security (Metasploit course): https://www.offensive-security.com/metasploit-unleashed/

  cybersecurity:
    name: Ethical hacking and cybersecurity
    Courses:
      Cybrary General Cybersecurity: https://www.cybrary.it/catalog/cybersecurity/
      Cybrary Ethical Hacking: https://www.cybrary.it/catalog/cybersecurity/ethical-hacking/
      Coursera cybersecurity courses: https://www.coursera.org/courses?query=cybersecurity
      Cisco NetAcad 'Introduction to Cybersecurity': https://www.netacad.com/courses/cybersecurity/introduction-cybersecurity
    Practice Sites:
      Hack This Site: https://www.hackthissite.org/
      Hack The Box: https://www.hackthebox.eu/
      PicoCTF: https://picoctf.org/
      CTF101 Database: https://ctf101.org/
      
  webdev:
    name: Web Development
    Websites:
      FreeCodeCamp: https://www.freecodecamp.org/
      The Odin Project: https://www.theodinproject.com/
      Jetbrains Academy: https://hyperskill.org/tracks/5

  js:
    name: JavaScript
    Documentation:
      JavaScript MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript
      The First Steps: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps
    Tutorials:
      JavaScript.info: https://javascript.info/
      30 Best Practices: https://code.tutsplus.com/tutorials/24-javascript-best-practices-for-beginners--net-5399
      40 Beginner Projects: https://www.freecodecamp.org/news/javascript-projects-for-beginners/
      14 Best JavaScript Books: https://www.guru99.com/javascript-books.html
    Other:
      16 Debugging Tips: https://raygun.com/learn/javascript-debugging-tips
      Best IDEs for JavaScript: https://dev.to/theme_selection/what-is-the-best-ide-for-javascript-development-in-2021-1pmn
      10+ Best JavaScript Frameworks: https://technostacks.com/blog/best-javascript-frameworks    

lang_aliases:
  python: py
  python3: py
  python2: py
  datascience: ds
  data science: ds
  data: ds
  ai: ds
  ml: ds
  machinelearning: ds
  machine learning: ds
  hacking: pentesting
  ethical-hacking: cybersecurity
  ethical hacking: cybersecurity
  capture the flag: cybersecurity
  ctf: cybersecurity
  javascript: js
