bot:
  prefix: "!"
  status: "for '!help' to show you all commands"

cogs:
  admin: true
  bump: true
  candidates: true
  challenges: true
  code_runner: true
  fun: true
  google: true
  help: true
  help_rotator: true
  kudos: true
  moderation: true
  onboarding: true
  python: true
  repeater: true
  rules: true
  settings: true
  spam: true
  statistics: true
  tips: true
  user_roles: true
  beginner_cog:
    enabled: true
    from: beginner.beginner

logging:
  format: "%(asctime)s: %(levelname)-9s %(name)-16s :: %(message)s"
  date_format: "%m/%d/%Y %I:%M:%S %p"
  level: WARN

resources:
  py:
    name: Python
    youtube:
      Corey Schafer: https://www.youtube.com/c/Coreyms/playlists
      Mosh: https://www.youtube.com/playlist?list=PLTjRvDozrdlxj5wgH4qkvwSOdHLOCx10f
    books:
      Automate the Boring Stuff with Python: https://automatetheboringstuff.com/2e/chapter0/
